#!/usr/bin/env python3

import click
import os
import sqlite3
import sys

DB_FILE = 'network.db'

def getdb(create=False):
    if os.path.exists(DB_FILE):
        if create:
            os.remove(DB_FILE)
    else:
        if not create:
            print('no database found')
            sys.exit(1)
    con = sqlite3.connect(DB_FILE)
    con.execute('PRAGMA foreign_keys = ON')
    return con

@click.group()
def cli():
    pass

@click.command()
def create():
    with getdb(create=True) as con:
        con.execute(
'''CREATE TABLE users (
    id          INTEGER PRIMARY KEY,
    email       TEXT NOT NULL
)''')
        con.execute(
'''CREATE UNIQUE INDEX users_email ON users (email)''')

        con.execute(
'''CREATE TABLE accounts (
    id          INTEGER PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    username    TEXT NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
)''')
        con.execute(
'''CREATE TABLE followers (
    id          INTEGER NOT NULL,
    follower_id     INTEGER NOT NULL,

    PRIMARY KEY (id, follower_id)
    FOREIGN KEY (id) REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY (follower_id) REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE
)''')
        con.execute(
'''CREATE TABLE posts (
    id          INTEGER PRIMARY KEY,
    text        TEXT NOT NULL,
    account_id  INTEGER NOT NULL,

    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE
)''')
        con.execute(
'''CREATE TABLE interests (
    id          INTEGER PRIMARY KEY,
    name        TEXT NOT NULL
)''')
        con.execute(
'''CREATE TABLE hasinterests (
    account_id       INTEGER NOT NULL,
    interest_id      INTEGER NOT NULL,

    PRIMARY KEY (account_id, interest_id)
    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY (interest_id) REFERENCES interests (id) ON DELETE CASCADE ON UPDATE CASCADE
)''')
    print('database created')

@click.command()
@click.argument('email')
def adduser(email):
    print('creating user with email address', email)
    with getdb() as con:
        cursor = con.cursor()
        cursor.execute('''INSERT INTO users (email) VALUES (?)''', (email,))
        id = cursor.lastrowid
        print(f'inserted with id={id}')

@click.command()
@click.argument('email')
@click.argument('username')
def addaccount(email, username):
    print('creating account with username', username, 'for email', email)
    with getdb() as con:
        cursor = con.cursor()
        cursor.execute('''INSERT INTO accounts (user_id, username)
VALUES ((SELECT id FROM users WHERE email = ?), ?)''', (email, username))
        id = cursor.lastrowid
        print(f'inserted with id={id}')

@click.command()
@click.argument('interest')
def addinterest(interest):
    print('creating interest with name', interest)
    with getdb() as con:
        cursor = con.cursor()
        cursor.execute('''INSERT INTO interests (name) VALUES (?)''', (interest,))
        id = cursor.lastrowid
        print(f'inserted with name={interest}')

cli.add_command(create)
cli.add_command(adduser)
cli.add_command(addaccount)
cli.add_command(addinterest)
cli()
